### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by wslyshptyc**
Created:
- basic HTML template for "Your Result:" (QUIC-16)
- section for Home, Ingredients input, and Recipe display page (QUIC-17)
- input fields and search button (QUIC-19)

### CODE REVIEW

**Review by Axello0 — CHANGES_REQUESTED** [review]
you added an extra div id="meal"

**Comment by wslyshptyc** [comment]
will soon be done

**Review by Axello0 — APPROVED** [review]
Good!

**Review by odeliadenise — APPROVED** [review]
great job, but the image needs to be adjusted (too big)

**Pull request merged**
